import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';
import Footer from '@/components/footer';

const inter = Inter({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const pushPenny = localFont({
  src: '../fonts/pushpenny.ttf',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${pushPenny.className} antialiased pb-10`}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
